# -*- coding: utf-8 -*-
"""3EP Advanced Calculator (Final Submission).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaD5ArSjS0-Nf0G4d8i_-01awnnWNYjl

Hi, if you want to try out the calculator, click on the Connect button on the top right. Then click on the Play button just below this cell.
"""

#3EP Advanced Calculator

#coordinate geometry
pi=3.142
def surfaceareaofsphere():
  r=float(input('Enter the radius of the sphere: '))
  surfacearea=(4)*(pi)*(r**2)
  print("The surface area of the sphere is",surfacearea)


def volumeofsphere():
    r=float(input('Enter the radius of the sphere: '))
    volume=(4/3)*(pi)*(r**3)
    print("The volume of the sphere is",volume)

def ivan_sphere():
  x=True
  while x==True:
    print('  ')
    option=int(input("What do you want to find for sphere? (1.Surface Area 2.Volume)(Enter 0 to quit): "))
    if option==1:
      surfaceareaofsphere()
    elif option==2:
      volumeofsphere()
    elif option==0:
      x=False
      print('You have quitted')
    else:
      print("Please choose an option")

#speed(julian)
def speed():
  dist=float(input("Enter the distance in km: "))
  time=float(input("Enter the time in h: "))
  spd=dist/time
  print("The speed is", spd,"km/h" )
def distance():
  spd=float(input("Enter the speed in km/h: "))
  time=float(input("Enter the time in h: "))
  dist=spd*time
  print("The distance is", dist, "km" )
def time():
  spd=float(input("Enter the speed in km/h: "))
  dist=float(input("Enter the distance in km: "))
  time=dist/spd
  print("The speed is", time,"h" )

def julian():
  end=0
  a=0
  while a != 1:
    qest_1=int(input("What do you wanna find? (type 1 for speed, 2 for distance, 3 for time and 0 to quit): "))
    if qest_1==1:
      speed()
    elif qest_1==2:
      distance()
    elif qest_1==3:
      time()
    elif qest_1==0:
      a=1


#grad(shion)
def grad():
  print("Gradient: ")
  y1 = int(input("Enter your Y1: "))
  x1 = int(input("Enter your X1: "))
  print()
  y2 = int(input("Enter your Y2: "))
  x2 = int(input("Enter your X2 : "))
  print()
  m = (y2 - y1) / (x2 - x1)
  print("The gradient of the line is ",m)



#dist(keane)
#√[(x2 – x1)^2 + (y2 – y1)^2]
def dis():
  print("Distance: ")
  x1=float(input("Enter your X1 "))
  y1=float(input("Enter your Y1 "))
  print()
  x2=float(input("Enter your X2 "))
  y2=float(input("Enter your Y2 "))
  print()

  distance=((x2-x1)**2+(y2-y1)**2)/((x2-x1)**2+(y2-y1)**2)
  print("The distance is",distance)
  print()







#eqn of line(Kester)
def eqnofline():
  print("Eqnation of the line: ")
  y1 = int(input("Enter your Y1: "))
  x1 = int(input("Enter your X1: "))
  y2 = int(input("Enter your Y2: "))
  x2 = int(input("Enter your X2: "))
  m = (y2 - y1) / (x2 - x1)
  c= y1 - (m * x1)
  print("The equation of the line is y =",m,"x +",c)
  print()



#midpoint(jingkai)
def mid():
 print("Midpoint: ")
 x1=int(input("Enter X1: "))
 x2=int(input("Enter X2: "))
 print()
 sum2=x1+x2
 hpoint=sum2/2
 print("midpoint is:",hpoint)
 y1=int(input("Enter Y1: "))
 y2=int(input("Enter Y2: "))
 print()
 sum1=y1+y2
 vpoint=sum1/2
 print("Midpoint is:",vpoint)
 print()

def cylinder():
  print("1.Volume of cylinder")
  print("2.Area of Cylinder")
  choice=int(input("Enter your choice(1 or 2):"))
  if choice==1:
    radius_cylinder=float(input("Enter the radius(cm):"))
    height_cylinder=float(input("Enter the height(cm):"))
    volume_cylinder=3.142*(radius_cylinder**2)*height_cylinder
    print("The volume of the cylinder:",round(volume_cylinder),"cm²")
  if choice==2:
    radius_cylinder=float(input("Enter the radius(cm):"))
    height_cylinder=float(input("Enter the height(cm):"))
    area_cylinder=((2*3.142*radius_cylinder*height_cylinder)+(2*3.142*(radius_cylinder**2)))
    print("The total surface area of the cylinder:",round(area_cylinder),"cm²")

def trap():
  print('choice 1: perimeter of trapezoid')
  print('choice 2: area of trapezoid')
  n1='stop'
  while n1 !=0:
    n1=int(input("choice: "))
    if n1 == 1:
      n1= int(input("Input length(cm): "))
      n2= int(input("Input length(cm): "))
      n3= int(input("Input length(cm): "))
      n4= int(input("Input length(cm): "))
      ans=(n1+n2+n3+n4)
      print(n1, "+", n2, "+", n3, "+", n4,'=', ans )
      print('the perimeter is '+ str(ans)+' cm')
    elif n1==2:
      n1= int(input("input first parallel side(cm): "))
      n2= int(input("input second parallel side(cm): "))
      n3= int(input('input height(cm): '))
      ans= (0.5*(n1+n2)*n3)
      print("the area is "+ str(ans)+'cm²')

def trapezium():
  print("Trapezium function")
  choice=int(input("Enter your choice(1 or 2):"))

  if choice==1:
    area=0
    x=int(input("Please enter the first parallel side: "))
    y=int(input("Please enter the second parallel side: "))
    z=int(input("Please enter the height of the trapezium: "))
    area=0.5*(x+y)*z
    print("The area of the trapezium is", area, ".")
    print("Area of Trapezium function")
    print()
  elif choice==2:
    peri=0
    a=int(input("Please enter the length of first side: "))
    b=int(input("Please enter the length of second side: "))
    c=int(input("Please enter the length of third side: "))
    d=int(input("Please enter the length of last side side: "))
    peri=a+b+c+d
    print("The perimeter of the trapezium is", peri, ".")
    print("Perimeter of Trapezium function")
    print()


def parallelogram():
  print()
  print("Parallelogram function")
  choice=int(input("Enter your choice(1 or 2):"))
  if choice==1:
    n1=float(input("Enter length: "))
    n2=float(input("Enter height: "))
    area_parallelogram=n1*n2
    print ("The area of the parallelogram is", area_parallelogram)
  elif choice==2:
    n1=float(input("Enter length: "))
    n2=float(input("Enter width: "))
    peri_parallalogram=2*n1+2*n2
    print(" The perimeter of the parallelogram is", peri_parallalogram)

def square():
  print('Square')
  choice=int(input("Enter your choice(1 or 2):"))
  if choice==1:
    print()
    print("Area of square")
    x=float(input("Please enter the length of one side of the square: "))
    area=x**2
    print("The area of the square is",area)

  elif choice==2:
    print()
    print("Perimeter of square")
    x=float(input("Please enter the length of one side of the square:"))
    peri=x*4
    print("The perimeter of the square is",peri)


def pythagoras_theorem():
  import math

  print('Pythagorean theorem calculator! Calculate your triangle sides.')
  print('Assume the sides are a, b, c and c is the hypotenuse (the side opposite the right angle)')
  formula = input('Which side (a, b, c) do you wish to calculate? side> ')

  if formula == 'c':
    side_a = float(input('Input the length of side a: '))
    side_b = float(input('Input the length of side b: '))

    side_c =float((side_b**2)+(side_a**2))**(0.5)

    print('The length of side c is: ' )
    print(side_c)

  elif formula == 'a':
      side_b = float(input('Input the length of side b: '))
      side_c = float(input('Input the length of side c: '))

      side_a = float((side_c**2)-(side_b**2))**(0.5)

      print('The length of side a is' )
      print(side_a)

  elif formula == 'b':
      side_a = float(input('Input the length of side a: '))
      side_c = float(input('Input the length of side c: '))

      side_b = float((side_c**2)-(side_a**2))**(0.5)

      print('The length of side b is')
      print(side_b)


def rectangle():
  print('Rectangle')
  opt=input("Calculate Area or perimeter(A/P): ")
  opt.upper()
  if opt=='A':
    length=int(input("enter the value of the length of the rectangle:  "))
    breadth=int(input("enter the value of the breadth of the rectangle: "))
    area=length*breadth
    print("The area of the rectangle is",area,)

  elif opt=='P':
    print()
    length=int(input("Enter the value of the length of the rectangle: "))
    breadth=int(input("Enter the value of the breadth of the rectangle: "))
    perimeter= length+length+breadth+breadth
    print("The perimeter of the rectangle is",perimeter,"cm")


def quadratic():
  a = float(input("a: "))
  b = float(input("b: "))
  c = float(input("c: "))
  discriminant = (b**2)-(4*a*c)
  if discriminant < 0:
    print("No real roots OR Line does not cut curve")
  elif discriminant == 0:
    print("Equal roots OR Line is a tangent to the curve")
  elif discriminant > 0:
    print("Real and distinct roots OR Line cuts curve at 2 distinct points")
  elif discriminant >= 0:
    print("Real roots OR Line cuts curve")
  if (a > 0) and (discriminant < 0):
    print("Curve is always positive/ above x-axis")
  if (a < 0) and (discriminant < 0):
    print("Curve is always negative/ below x-axis")
  if a == 0:
    print("")
    print("Not a quadratic equation, please try again")
    print("")
  if a > 0:
    if discriminant > 0 or discriminant < 0:
      x1 = ((-b) + (discriminant**(1/2))) / (2*a)
      x2 = ((-b) - (discriminant**(1/2))) / (2*a)
      xs = (x1+x2) / 2
      ys = (a*(xs**2)) + (b*xs) + c
      print("")
      print("x =", x1, "or", x2)
      print("")
      print("y-intercept =", c)
      print("")
      print("Coordinates of minimum point")
      print("x: ", xs)
      print("y: ", ys)
      print("")
    elif discriminant == 0:
      x = (-b) / (2*a)
      ys = (a*(x**2)) + (b*x) + c
      print("")
      print("x =", x)
      print("")
      print("y-intercept =", c)
      print("")
      print("Coordinates of minimum point")
      print("x: ", x)
      print("y: ", ys)
      print("")
  else:
    print('Please select a side between a, b, c')

def circle():
  print('Circle')
  opt=int(input("1.Calculate Area or 2.Arc Length(1/2): "))
  if opt==1:
    r=int(input("what is the radius of the circle(in cm): "))
    deg=int(input("what is the degree of the sector of the circle(in degrees): "))
    a=round(pi*r*(deg/360)*r,2)
    print("The area of the sector is" ,a)
  elif opt==2:
    print()
    r=int(input("what is the radius of the circle(in cm): "))
    deg=int(input("what is the degree of the sector of the circle(in degrees): "))
    al=round(pi*2*r*(deg/360),2)
    p=al+r
    print("the arc length of the sector is" ,al, 'cm and the perimeter of the sector is' ,p)

def triangle():
    x= 'yo'
    while x!=0:
      x=int(input('1.Area or 2.Perimeter? (1 / 2 / 0 to quit) '))
      if x==1:
        print("Area of Triangle")
        Base=int(input('Enter the base of the triangle: '))
        Height=int(input('Enter the height of the triangle:'))
        sum=0.5*(Base)*(Height)
        print('The area of the triangle is',sum)
      elif x==2:
        print('Perimeter of Triangle')
        Side1=int(input('Enter the length of the first side in centimeter:'))
        Side2=int(input('Enter the length of the second side in centimeter:'))
        Side3=int(input('Enter the length of the third side in centimeter'))
        total=Side1+Side2+Side3
        print('The perimeter of the triangle is',total)
      elif x==0:
        x=0



#triangle,circle,cone,sphere
list1=['Quadratic Equations','Coordinate Geometry','Plane Geometry','Speed']
listcord=['Gradient (m)','Midpoint (M)','Distance 2 points (A,B)','Equation of a line']
listplane=['Trapezium','Square','Rectangle','Triangle','Trapezoid','Parallelogram','Circle','Cylinder','Cone','Sphere',"Pythagora's Theorem"]
def main():
  for i in range(len(list1)):
    print(i+1,')',list1[i])
def subcord():
  for i in range(len(listcord)):
    print(i+1,')',listcord[i])
def subplane():
  for i in range(len(listplane)):
    print(i+1,')',listplane[i])

check=True
while check==True:
  try:
    main()
    num=int(input('Please select an option 1 to 4 (0 to quit): '))
    print(' ')
    if num==1:
      quadratic()
    elif num==2:
      subcord()
      num2=int(input('Please select an option 1 to 4: '))
      if num2==1:
        grad()
      elif num2==2:
        mid()
      elif num2==3:
        dis()
      elif num2==4:
        eqnofline()
    elif num==3:
      subplane()
      num2=int(input('Please select an option 1 to 11 (0 to quit): '))
      if num2==1:
        trapezium()
      elif num2==2:
        square()

      elif num2==3:
        rectangle()

      elif num2==4:
        triangle()
      elif num2==5:
        trap()
      elif num2==6:
        parallelogram()
      elif num2==7:
        circle()
      elif num2==8:
        cylinder()
      elif num2==9:
        pass #cone0

      elif num2==10:
        ivan_sphere()
      elif num2==11:
        pythagoras_theorem()
    elif num==4:
      julian()
    elif num==0:
      print('End of program')
      check=False
  except:
    ValueError
    continue